# Generated by Django 3.1.5 on 2021-01-15 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedtour',
            old_name='arrival_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='bookedtour',
            old_name='departure_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='price',
            new_name='price_for_day',
        ),
        migrations.RemoveField(
            model_name='bookedtour',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='bookedtour',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='adult',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type_of_food',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Без питания'), (2, 'Скромный завтрак'), (3, 'Завтрак'), (4, 'Завтрак + ужин'), (5, 'Завтрак + обед + ужин'), (6, 'Все включено')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_right',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пользователь'), (1, 'Турменеджер'), (2, 'Админ')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.document'),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count_days', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.airline')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotels_photos')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fav_tours',
            field=models.ManyToManyField(through='app.FavouriteTour', to='app.Tour'),
        ),
        migrations.AlterField(
            model_name='bookedtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour'),
        ),
        migrations.DeleteModel(
            name='TourCatalog',
        ),
    ]
