# Generated by Django 3.1.3 on 2021-01-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210110_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedtour',
            old_name='arrival_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='bookedtour',
            old_name='departure_date',
            new_name='start',
        ),
    ]
