# Generated by Django 3.1.3 on 2021-01-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210111_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.PositiveIntegerField(default='5'),
            preserve_default=False,
        ),
    ]
