# Generated by Django 3.1.3 on 2021-01-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tour_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.city'),
            preserve_default=False,
        ),
    ]
