# Generated by Django 3.1.3 on 2021-01-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tour_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedtour',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='bookedtour',
            old_name='start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='days',
            new_name='count_days',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
    ]
