# Generated by Django 3.1.3 on 2021-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210111_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type_of_food',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Без питания'), (2, 'Скромный завтрак'), (3, 'Завтрак'), (4, 'Завтрак + ужин'), (5, 'Завтрак + обед + ужин'), (6, 'Все включено')]),
        ),
    ]
