# Generated by Django 3.1.3 on 2021-01-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210112_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='price',
            new_name='price_for_day',
        ),
        migrations.RemoveField(
            model_name='bookedtour',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='bookedtour',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='adult',
        ),
        migrations.AddField(
            model_name='tour',
            name='airline',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='app.airline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.insurance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_right',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пользователь'), (1, 'Турменеджер'), (2, 'Админ')], default=0),
        ),
        migrations.CreateModel(
            name='FavouriteTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
