# Generated by Django 3.1.3 on 2021-01-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210112_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_tours',
            field=models.ManyToManyField(through='app.FavouriteTour', to='app.Tour'),
        ),
    ]
