# Generated by Django 3.1.3 on 2021-01-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_fav_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.document'),
        ),
    ]
