# Generated by Django 3.1.3 on 2021-01-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210113_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.document'),
        ),
    ]
