# Generated by Django 3.1.3 on 2021-01-17 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hotelphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Паспорт'), (1, 'Загранпаспорт')], default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='some description', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RatingTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '0.5'), (2, '1'), (3, '1.5'), (4, '2'), (5, '2.5'), (6, '3'), (7, '3.5'), (8, '4'), (9, '4.5'), (10, '5')])),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.ManyToManyField(through='app.RatingTour', to=settings.AUTH_USER_MODEL),
        ),
    ]
