# Generated by Django 3.1.3 on 2021-01-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210117_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type_of_food',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Без питания'), (2, 'Завтрак'), (3, 'Завтрак + ужин'), (4, 'Завтрак + обед + ужин'), (5, 'Все включено')]),
        ),
    ]
