# Generated by Django 3.1.3 on 2021-01-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210117_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='visa_availability',
        ),
    ]
