# Generated by Django 3.1.3 on 2021-01-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_document_visa_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Паспорт'), (2, 'Загранпаспорт')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_right',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пользователь'), (2, 'Турменеджер'), (3, 'Админ')], default=0),
        ),
    ]
