# Generated by Django 3.1.3 on 2021-01-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210117_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.hotel'),
        ),
    ]
