# Generated by Django 3.1.3 on 2021-01-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210118_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
    ]
