# Generated by Django 3.1.3 on 2021-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_for_night',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='price_for_day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
