# Generated by Django 3.1.3 on 2021-01-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210119_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelphoto',
            name='photo',
            field=models.ImageField(upload_to='hotels_photos'),
        ),
    ]
