# Generated by Django 3.1.3 on 2021-01-19 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210119_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelphoto',
            name='photo',
            field=models.ImageField(upload_to='hotels_photos', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
